// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2p5--aCnq5M5acpVo8O7LctE1dRW6New',
    appId: '1:944958994994:web:702d4b42764efea8d75a2b',
    messagingSenderId: '944958994994',
    projectId: 'e-commerce-app-1f850',
    authDomain: 'e-commerce-app-1f850.firebaseapp.com',
    storageBucket: 'e-commerce-app-1f850.firebasestorage.app',
    measurementId: 'G-EM77T76DZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk8ZH6k7tx-HBtobehnhH5wtjb4oKQR0U',
    appId: '1:944958994994:android:51d6323382af36c2d75a2b',
    messagingSenderId: '944958994994',
    projectId: 'e-commerce-app-1f850',
    storageBucket: 'e-commerce-app-1f850.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB04jNIoB6sY9TMhviVucKMkgTptvbYVrM',
    appId: '1:944958994994:ios:310aefce6572e9f0d75a2b',
    messagingSenderId: '944958994994',
    projectId: 'e-commerce-app-1f850',
    storageBucket: 'e-commerce-app-1f850.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB04jNIoB6sY9TMhviVucKMkgTptvbYVrM',
    appId: '1:944958994994:ios:310aefce6572e9f0d75a2b',
    messagingSenderId: '944958994994',
    projectId: 'e-commerce-app-1f850',
    storageBucket: 'e-commerce-app-1f850.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2p5--aCnq5M5acpVo8O7LctE1dRW6New',
    appId: '1:944958994994:web:a8398c1d0c37345ad75a2b',
    messagingSenderId: '944958994994',
    projectId: 'e-commerce-app-1f850',
    authDomain: 'e-commerce-app-1f850.firebaseapp.com',
    storageBucket: 'e-commerce-app-1f850.firebasestorage.app',
    measurementId: 'G-JZYYKKHQVV',
  );

}